language: go

services:
  - docker

before_install:
  - docker-compose pull
  - docker-compose up -d

install:
  - docker-compose exec php make install

script:
  - docker-compose exec php make build

after_success:
  - docker-compose exec php make coverage
  - curl -L --output php-coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - ls php-coveralls.phar
  - travis_retry php-coveralls.phar --coverage_clover=./tmp/report/clover.xml --json_path=./tmp/report/coveralls-upload.json